export { default as Login } from './Login'
export { default as Home } from './Home'
export { default as Diagnose } from './HospitalDiagnose'
export { default as DoctorDiag } from './DoctorDiagnose'
export { default as Maps } from './Maps'
